create table if not exists public.admin_master_audit_logs (
  id bigint generated by default as identity primary key,
  admin_auth_user_id uuid not null,
  action text not null,
  target_table text not null,
  target_id text not null,
  before_snapshot jsonb not null default '{}'::jsonb,
  after_snapshot jsonb not null default '{}'::jsonb,
  reason text not null,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.admin_master_audit_logs enable row level security;

revoke all on table public.admin_master_audit_logs from anon, authenticated;

create index if not exists admin_master_audit_logs_admin_created_idx
  on public.admin_master_audit_logs (admin_auth_user_id, created_at desc);

create index if not exists admin_master_audit_logs_target_idx
  on public.admin_master_audit_logs (target_table, target_id, created_at desc);

create index if not exists admin_master_audit_logs_action_idx
  on public.admin_master_audit_logs (action, created_at desc);
