create table if not exists public.assinaturas_asaas (
  id bigint generated by default as identity primary key,
  owner_type text not null default 'unresolved',
  owner_resolution_source text null,
  auth_user_id text null,
  clinica_id text null,
  customer_name text null,
  customer_email text null,
  customer_document text null,
  asaas_customer_id text null,
  asaas_subscription_id text not null,
  asaas_payment_id text null,
  plano_slug text not null,
  status_assinatura text not null default 'PENDING',
  payment_status text null,
  valor_plano numeric(10,2) not null default 0,
  proximo_vencimento date null,
  forma_pagamento text null,
  assinatura_ativa boolean not null default false,
  last_event_id text null,
  last_event_type text null,
  asaas_payload jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint assinaturas_asaas_asaas_subscription_id_key unique (asaas_subscription_id)
);

create index if not exists assinaturas_asaas_auth_user_id_idx
  on public.assinaturas_asaas (auth_user_id);

create index if not exists assinaturas_asaas_clinica_id_idx
  on public.assinaturas_asaas (clinica_id);

create index if not exists assinaturas_asaas_customer_email_idx
  on public.assinaturas_asaas (customer_email);

create index if not exists assinaturas_asaas_customer_document_idx
  on public.assinaturas_asaas (customer_document);

create index if not exists assinaturas_asaas_asaas_customer_id_idx
  on public.assinaturas_asaas (asaas_customer_id);

alter table public.assinaturas_asaas enable row level security;

create table if not exists public.asaas_webhook_events (
  id bigint generated by default as identity primary key,
  event_id text not null,
  event_type text not null,
  processing_status text not null default 'processing',
  asaas_subscription_id text null,
  asaas_payment_id text null,
  payload jsonb not null default '{}'::jsonb,
  error_message text null,
  attempts integer not null default 1,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  processed_at timestamptz null,
  constraint asaas_webhook_events_event_id_key unique (event_id)
);

create index if not exists asaas_webhook_events_subscription_id_idx
  on public.asaas_webhook_events (asaas_subscription_id);

create index if not exists asaas_webhook_events_event_type_idx
  on public.asaas_webhook_events (event_type);

alter table public.asaas_webhook_events enable row level security;

alter table if exists public.clinicas
  add column if not exists asaas_customer_id text,
  add column if not exists asaas_subscription_id text,
  add column if not exists plano_slug text,
  add column if not exists status_assinatura text,
  add column if not exists valor_mensal numeric(10,2),
  add column if not exists proximo_vencimento date,
  add column if not exists forma_pagamento text,
  add column if not exists assinatura_ativa boolean not null default false;

create index if not exists clinicas_asaas_subscription_id_idx
  on public.clinicas (asaas_subscription_id);

alter table if exists public.usuarios
  add column if not exists asaas_customer_id text,
  add column if not exists asaas_subscription_id text,
  add column if not exists plano_slug text,
  add column if not exists status_assinatura text,
  add column if not exists valor_mensal numeric(10,2),
  add column if not exists proximo_vencimento date,
  add column if not exists forma_pagamento text,
  add column if not exists assinatura_ativa boolean not null default false;

create index if not exists usuarios_asaas_subscription_id_idx
  on public.usuarios (asaas_subscription_id);
